config/routes.rb
SelectionManager::Application.routes.draw do

  resources :candidates do
    resources :avaliations
  end

  get "home/inscricao"

  resources :roles

  resources :selections do
    resources :candidates, :except => :index
  end
  
  
  devise_for :users

  resources :users

  
  resources :enterprises

  resources :selections do
    resources :steps, :except => :index
  end

  root :to => 'home#index'

end

app/models/avaliation.rb
class Avaliation < ActiveRecord::Base
  belongs_to :candidate
  attr_accessible :avaliation, :step
end

app/controllers/avaliations_controller.rb
#encoding: utf-8

class AvaliationsController < ApplicationController
  # GET /avaliations
  # GET /avaliations.json
  def index
    @avaliations = Avaliation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @avaliations }
    end
  end

  # GET /avaliations/1
  # GET /avaliations/1.json
  def show
    @avaliation = Avaliation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @avaliation }
    end
  end

  # GET /avaliations/new
  # GET /avaliations/new.json
  def new
    @avaliation = Avaliation.new
    @candidate = Candidate.find(params[:candidate_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @avaliation }
    end
  end

  # GET /avaliations/1/edit
  def edit
    @avaliation = Avaliation.find(params[:id])
  end

  # POST /avaliations
  # POST /avaliations.json
  def create
    #@avaliation = Avaliation.new(params[:avaliation])
    @candidate = Candidate.find(params[:candidate_id])
    @avaliation = @candidate.avaliations.create(params[:avaliation])
    
    respond_to do |format|
      if @avaliation.save
        format.html { redirect_to candidate_avaliation_path(@avaliation.candidate, @avaliation), notice: 'Avaliation was successfully created.' }
        format.json { render json: @avaliation, status: :created, location: @avaliation }
      else
        format.html { render action: "new" }
        format.json { render json: @avaliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /avaliations/1
  # PUT /avaliations/1.json
  def update
    @avaliation = Avaliation.find(params[:id])

    respond_to do |format|
      if @avaliation.update_attributes(params[:avaliation])
        format.html { redirect_to @avaliation, notice: 'Avaliation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @avaliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliations/1
  # DELETE /avaliations/1.json
  def destroy
    @avaliation = Avaliation.find(params[:id])
    @avaliation.destroy

    respond_to do |format|
      format.html { redirect_to avaliations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/avaliations_helper.rb
module AvaliationsHelper
end

app/views/avaliations/_form.html.erb
<%= form_for(@avaliation) do |f| %>
  <% if @avaliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avaliation.errors.count, "error") %> prohibited this avaliation from being saved:</h2>

      <ul>
      <% @avaliation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :step %><br />
    <%= f.number_field :step %>
  </div>
  <div class="field">
    <%= f.label :avaliation %><br />
    <%= f.text_area :avaliation %>
  </div>
  <div class="field">
    <%= f.label :candidate %><br />
    <%= f.text_field :candidate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avaliations/edit.html.erb
<h1>Editing avaliation</h1>

<%= render 'form' %>

<%= link_to 'Show', @avaliation %> |
<%= link_to 'Back', avaliations_path %>

app/views/avaliations/index.html.erb
<h1>Listing avaliations</h1>

<table>
  <tr>
    <th>Step</th>
    <th>Avaliation</th>
    <th>Candidate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @avaliations.each do |avaliation| %>
  <tr>
    <td><%= avaliation.step %></td>
    <td><%= avaliation.avaliation %></td>
    <td><%= avaliation.candidate %></td>
    <td><%= link_to 'Show', avaliation %></td>
    <td><%= link_to 'Edit', edit_avaliation_path(avaliation) %></td>
    <td><%= link_to 'Destroy', avaliation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Avaliation', new_avaliation_path %>

app/views/avaliations/new.html.erb
<h1>New avaliation</h1>

<%= render 'form' %>

<%= link_to 'Back', avaliations_path %>

app/views/avaliations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Step:</b>
  <%= @avaliation.step %>
</p>

<p>
  <b>Avaliation:</b>
  <%= @avaliation.avaliation %>
</p>

<p>
  <b>Candidate:</b>
  <%= @avaliation.candidate %>
</p>


<%= link_to 'Edit', edit_avaliation_path(@avaliation) %> |
<%= link_to 'Back', avaliations_path %>