config/routes.rb
SelectionManager::Application.routes.draw do

  resources :candidates do
    resources :avaliations
  end

  get "home/inscricao"

  resources :roles

  resources :selections do
    resources :candidates, :except => :index
  end
  
  
  devise_for :users

  resources :users

  
  resources :enterprises

  resources :selections do
    resources :steps, :except => :index
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<div>
			<% if !current_user %>
			<div class="row">
				<div class="span4">
					<div class="hero-unit card-home card-admin">
						<h1>
							Administração
						</h1>
						<p>
							Painel de administração para membros da empresa
						</p>
						<p>
							<a class="btn btn-large" href="/users/sign_in">Login »</a>
						</p>
					</div>
				</div>
				<div class="span4">
					<div class="hero-unit card-home card-subscribe">
						<h1>
							Inscrição
						</h1>
						<p>
							Formulário de inscrição para o processo seletivo corrente
						</p>
						<p>
							<a class="btn btn-large" href="/home/inscricao">Inscrever-se »</a>
						</p>
					</div>
				</div>
				<div class="span4">
					<div class="hero-unit card-home card-results">
						<h1>
							Resultados
						</h1>
						<p>
							Lista de aprovados nos processos seletivos anteriores
						</p>
						<p>
							<a class="btn btn-large" href="#">Visualizar »</a>
						</p>
					</div>
				</div>
			</div>

			<% else %>

			<h1>Bem-Vindo!</h1>

			<p><b>Empresa:</b> <%= current_user.enterprise.name %></p>

			<p><b>Seleções:</b></p>
			<ul>
				<% current_user.enterprise.selection.each do |selections| %>

					<li><%= selections.title %> <%= link_to "Detalhes", selections %> <%= link_to "Editar", edit_selection_path(selections) %></li>
						
							<% selections.steps.each do |steps| %>
								<ul>
								
								<li><%= steps.title %> <%= link_to "Editar", edit_selection_step_path(steps.selection, steps) %></li>
								
								</ul>
							<% end %>
						
				<% end %>
			</ul>
			<p> <%= link_to "Criar Nova Seleção", new_selection_path %> </p>

			<% end %>
			<div class="row">
				<div class="span12">
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/inscricao.html.erb
<h1 class="subscribe-title">Inscrições</h1>
<div class="form-container">
  <table>
    <tr>
      <th class="span5">Processo seletivo</th>
      <th class="span3">Data final</th>
      <th class="span4">Descrição</th>
      <th></th>
    </tr>
  <% @selections = Selection.all %>
  <% @selections.each do |s| %>
    <tr>
      <td><%= s.title %></td>
      <td><%= s.entries_end_date %></td>
      <td><%= s.description %></td>
      <td class="subscribe-btn"><%= link_to 'Inscrever-se', new_selection_candidate_path(s) %></td>      
    </tr>
  <% end %>
  </table>

  <br />
</div>