config/routes.rb
SelectionManager::Application.routes.draw do

  resources :candidates do
    resources :avaliations
  end

  get "home/inscricao"

  resources :roles

  resources :selections do
    resources :candidates, :except => :index
  end
  
  
  devise_for :users

  resources :users

  
  resources :enterprises

  resources :selections do
    resources :steps, :except => :index
  end

  root :to => 'home#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  attr_accessible :about, :email, :facebook, :name, :telephone
  belongs_to :selection
  has_many :avaliations
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new
    @selection = Selection.find(params[:selection_id])


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
    @selection = @candidate.selection

  end

  # POST /candidates
  # POST /candidates.json
  def create
    @selection = Selection.find(params[:selection_id])
    @candidate = @selection.candidates.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to :root, notice: 'Candidato Cadastrado' }      
      else
        format.html { render action: "new" }        
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @selection_candidate_path, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to selection_path(params[:selection_id]) }
      format.json { head :no_content }
    end
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= simple_form_for([@selection, @candidate], :html => { :class => 'form-horizontal' ,  :multipart => true }) do |f| %>

      <%= f.input :name, label: 'Nome' %>
      <%= f.input :email, label: 'Email' %>      
      <%= f.input :facebook, label: 'Facebook' %>
      <%= f.input :telephone, label: 'Telefone' %>
      <%= f.input :about, label: 'Fale um pouco sobre você', :input_html => {
      	:style => 'width: 280px; height: 200px'} %>
          
      <%= f.button :submit, :class => 'btn btn-primary' %>
      <a href="/" class="btn btn-primary">Cancelar</a>      
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %> |
<%= link_to 'Delete', @candidate, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/candidates/index.html.erb
<h1>Candidatos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Telepone</th>
    <th>Facebook</th>
    <th>Sobre</th>
    <th></th>
    <th></th>
  </tr>

<% @candidates.each do |candidate| %>
  <tr>
    <td><%= candidate.name %></td>
    <td><%= candidate.email %></td>
    <td><%= candidate.telephone %></td>
    <td><%= candidate.facebook %></td>
    <td><%= candidate.about %></td>
    <td><%= link_to 'Show', candidate %></td>
    <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>Inscrição</h1>
<div class="form-container">
	<div class="row">
  		<div class="form-card">  
			<%= render 'form' %>
		</div>
	</div>
</div>
<%= link_to 'Back', selection_candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @candidate.name %>
</p>

<p>
  <b>Email:</b>
  <%= @candidate.email %>
</p>

<p>
  <b>Telephone:</b>
  <%= @candidate.telephone %>
</p>

<p>
  <b>Facebook:</b>
  <%= @candidate.facebook %>
</p>

<p>
  <b>About:</b>
  <%= @candidate.about %>
</p>

<h2>Avaliações</h2>
<% @candidate.avaliations.each do |avaliation| %>
  <p>
    <strong>Etapa:</strong>
    <%= avaliation.step %>
  </p>
 
  <p>
    <strong>Avaliação:</strong>
    <%= avaliation.avaliation %>
  </p>
<% end %>

<p>Adicionar avaliação:</p>
<%= form_for([@candidate, @candidate.avaliations.build]) do |f| %>
  <p>
    <%= f.label :step %><br />
    <%= f.number_field :step %>
  </p>
  <p>
    <%= f.label :avaliation %><br />
    <%= f.text_area :avaliation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Edit', edit_selection_candidate_path(@candidate) %> |
<%= link_to 'Back', home_inscricao_path %>