config/routes.rb
SelectionManager::Application.routes.draw do

  resources :candidates do
    resources :avaliations
  end

  get "home/inscricao"

  resources :roles

  resources :selections do
    resources :candidates, :except => :index
  end
  
  
  devise_for :users

  resources :users

  
  resources :enterprises

  resources :selections do
    resources :steps, :except => :index
  end

  root :to => 'home#index'

end

app/models/selection.rb
class Selection < ActiveRecord::Base
  attr_accessible :description, :title, :entries_end_date, :enterprise_id
  has_many :steps, :dependent => :restrict 
  #aqui estou dizendo que seleçao pode ter muitos etapas, 
  #mas que se existir alguma etapa com um seleção, essa seleção nao pode ser deletada(:dependent => :restrict).
  has_many :candidates
  belongs_to :enterprise #Cada seleção pertence a uma empresa.
  validates_presence_of :enterprise_id

end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  # GET /selections
  # GET /selections.json
  load_and_authorize_resource
  def index
    @selections = Selection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @selections }
    end
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
    @selection = Selection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/new
  # GET /selections/new.json
  def new
    @selection = Selection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/1/edit
  def edit
    @selection = Selection.find(params[:id])
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(params[:selection])

    respond_to do |format|
      if @selection.save
        format.html { redirect_to @selection, notice: 'Selection was successfully created.' }
        format.json { render json: @selection, status: :created, location: @selection }
      else
        format.html { render action: "new" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /selections/1
  # PUT /selections/1.json
  def update
    @selection = Selection.find(params[:id])

    respond_to do |format|
      if @selection.update_attributes(params[:selection])
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection = Selection.find(params[:id])
    @steps = @selection.steps
    @steps.destroy_all
    @candidates = @selection.candidates
    @candidates.destroy_all
    @selection.destroy

    respond_to do |format|
      format.html { redirect_to selections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.erb
<%= simple_form_for(@selection, :html => { :class => 'form-horizontal' }) do |f| %>

  		<%= f.input :title, label: 'Nome' %>

  		<%= f.input :description, label: 'Descrição', :input_html => {:style => 'width: 500px; height: 200px'} %>
  		<%= f.input :entries_end_date, label: 'Prazo final para inscrições', order: [:day,:month, :year], :input_html => {:style => 'width: auto'} %>
  		<%= f.select :enterprise_id ,Enterprise.find(current_user.enterprise_id).name => current_user.enterprise_id	%>



  		<div class="form-actions">
    	<%= f.button :submit, :class => 'btn btn-primary' %>
    	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                selections_path, :class => 'btn btn-info' %>
  		</div>
<% end %>

app/views/selections/edit.html.erb
<h1><%= t('titles.selections.edit') %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), selections_path %> |
<%= link_to t('actions.delete'), @selection, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/selections/index.html.erb
<h1>Processos seletivos</h1>
  <% if @selections.count.zero? %>
    <p><h4>Não há processos seletivos cadastrados!</h4></p>
  <% else %>
    <table>
      <tr>
        <th>Title</th>
        <% if can? :manage, 'users' %>
          <th>Enterprise</th>
        <% end %>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @selections.each do |selection| %>
      <% if selection.enterprise_id == current_user.enterprise_id or current_user.enterprise_id.eql?1 %>
        <tr>
          <td><%= selection.title %></td>
          <% if can? :manage, 'users' %>
            <td><%= Enterprise.find(selection.enterprise_id).name %></td>
          <% end %>
          <td></td>
          <td><%= link_to 'Detalhes', selection %>  </td>
          <td><%= link_to 'Editar', edit_selection_path(selection) %>  </td>
          <td><%= link_to 'Excluir', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
    </table>
  <% end %>
<br />

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render 'form' %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>
<% if @selection.enterprise_id == current_user.enterprise_id or current_user.enterprise_id.eql?1 %>
	<h2> Processo Seletivo: <%= @selection.title %> </h2>

	<h3> <%= @selection.description %></h3>

	
	<!--<% for candidates in Candidate.find(:all,:conditions =>["selection_id LIKE :current",{:current => @selection.id}]) %>
		<%= candidates.name%>
	<% end %>
-->
	<%@candidatos = @selection.candidates%>

	<%if !@candidatos.count.zero? %>	
		<table>
			<thead>
				<th>Candidatos</th>
				<th>Dados</th>
				<th>Selecionar para próxima etapa</th>
			</thead>
			<tbody>
		<%@candidatos.each do |c| %>
				<td>				
					<%= c.name%>				
				</td>	
				<td>
					<%= link_to 'Dados', selection_candidate_path(c.selection, c) %>
				</td>
				<td>
								
				</td>
			</tbody>		
		<% end %>
		</table>
	<%end%>

	<% if @selection.steps.count.zero? %>
		<p><h4>Não há etapas cadastradas!</h4></p>
	<% else %>
		<p><h4>Etapas cadastradas:</h4>
		<table>
			<tr>
				<th>Etapa:</th>
				<th>Hora:</th>
				<th>Data:</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>		
			
		<% @selection.steps.each do |step| %>
  			<tr>
    			<td><%= step.title %></td>
    			<% @hora = step.hour %>
    			<% @hora.to_s%>
    			<td><%= @hora.strftime "%H:%M" %></td>
    			<% @data = step.date %>
    			<% @data.to_s %>
    			<td><%= @data.strftime "%d/%m/%Y" %></td>
	    		<td><%= link_to 'Detalhes', selection_step_path(step.selection, step) %></td>
	    		<td><%= link_to 'Editar', edit_selection_step_path(step.selection, step) %></td>
	    		<td><%= link_to 'Excluir', step.selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  			</tr>
		<% end %>
		</table>
	<% end %>
<br>
<%= link_to 'Nova Etapa', new_selection_step_path(@selection) %> | 
<%= link_to 'Editar', edit_selection_path(@selection) %> |
<%= link_to 'Voltar', selections_path %>
<% else %>
	<% redirect_to root_url %>
<% end %>